---
- name: Clone frontend repository
  git:
    repo: https://github.com/Cr0me1ve/lab1_front.git
    dest: /app/frontend/

- name: Clone backend repository
  git:
    repo: https://github.com/Cr0me1ve/lab1_back.git
    dest: /app/backend/

- name: Clone DevOps repository
  git:
    repo: https://github.com/Cr0me1ve/lab2_docker.git
    dest: /app/devops/
