---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker Compose is installed
      pip:
        name: docker-compose
        state: present
