---
- name: Install Docker and Docker Compose
  apt:
    update_cache: yes
    name:
      - docker.io
      - python3-pip
  become: yes
  tags:
    - deploy

- name: Download Docker Compose script
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
  become: yes
  tags:
    - deploy

- name: Make Docker Compose executable
  file:
    path: /usr/local/bin/docker-compose
    mode: '0755'
  become: yes
  tags:
    - deploy
