---
- name: Install Docker and Docker Compose
  apt:
    update_cache: yes
    name:
      - docker.io
      - python3-pip
  become: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
