---
- name: Install Docker and Docker Compose
  apt:
    name:
      - python3-pip
      - docker.io
    state: present
  become: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
